### ISSUE TITLE
refine requirements.txt

### ISSUE THREAD

**Issue by LoQiseaking69** [HermiTech-L3C/QSys-Design#1]
Traceback (most recent call last):
  File "C:\Users\antho\OneDrive\Desktop\HTDA\QSys-Design\Qros.py", line 6, in <module>
    from qiskit import QuantumCircuit, execute, Aer
ImportError: cannot import name 'execute' from 'qiskit' (C:\Users\antho\OneDrive\Desktop\HTDA\QSys-Design\QC\Lib\site-packages\qiskit\__init__.py)

**Comment by LoQiseaking69** [comment]
first commit was at 3Am.... obv i'll get it cuz who's even listening.

**Comment by seethen1y** [comment]
there r such less information online of this error have you solve it?
Traceback (most recent call last):
File "c:\Users\26772\Desktop\program_test\demo.py", line 2, in <module>
from qiskit import QuantumCircuit, execute
ImportError: cannot import name 'execute' from 'qiskit' (D:\python\Lib\site-packages\qiskit\__init__.py)

**Comment by seethen1y** [comment]
i m mad with the problem🤬

**Comment by seethen1y** [comment]
well it seems i found the solution lol🤣
here is the official explanation：

**For example, instead of running:**
_from giskit import execute
job =execute(circuit,backend)_
**you can run:**
_from giskit import transpile
new circuit = transpile(circuit，backend)
iob = backend.run(new circuit)_

and i also found myself straightly using  _bakend.run()_  instead _of execute(backend)_ also work
hope it really help you
